export const FETCH_DATA_BEGIN   = 'FETCH_DATA_BEGIN';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DID_SUCCESS  = 'FETCH_DID_SUCCESS';
export const FETCH_RULES_SUCCESS = 'FETCH_RULES_SUCCESS';
export const FETCH_IVR_SUCCESS  = 'FETCH_IVR_SUCCESS';
export const FETCH_HOURS_SUCCESS = 'FETCH_HOURS_SUCCESS';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_DID = 'FETCH_DID';
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS';
export const FETCH_EXTENSION_SUCCESS = 'FETCH_EXTENSION_SUCCESS';
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';
export const FETCH_EXTENSION_SEARCH_SUCCESS = 'FETCH_EXTENSION_SEARCH_SUCCESS';
export const FETCH_TAB = 'FETCH_TAB';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';
export const FETCH_REPORT_SMS_SUCCESS = 'FETCH_REPORT_SMS_SUCCESS';
export const FETCH_REPORT_CALL_SUCCESS = 'FETCH_REPORT_CALL_SUCCESS';
export const FETCH_ACCESS_SUCCESS = 'FETCH_ACCESS_SUCCESS';
export const FETCH_EXTENSION_NOT_IN_TEAM_SUCCESS = 'FETCH_EXTENSION_NOT_IN_TEAM_SUCCESS';


